server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100000000
      maxRequestSize: 200000000
  thymeleaf:
    cache : false
    mode: HTML5
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/kg?useSSL=false&serverTimezone=UTC}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    type: com.zaxxer.hikari.HikariDataSource
custom:
  neo4j:
    url: ${NEO4J_URL:bolt://localhost:7687}
    username: ${NEO4J_USERNAME:neo4j}
    password: ${NEO4J_PASSWORD:123456}
  file:
    serverurl:  http://localhost:8089
    location : D:\\kgmanager\\csv\\   #如果是Windows情况下，格式是 D:\\kgmanager\\csv\\   linux 格式"/home/kgmanager/csv/";
mybatis:
  typeAliasesPackage: com.warmer.kgmaker.entity
  mapperLocations: classpath*:/mapping/*.xml
#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

